export let GLOBAL = {};

GLOBAL['BASE_URL'] = 'http://172.16.3.104:3000';
GLOBAL['HTTP_METHOD_GET'] = 'GET';
GLOBAL['HTTP_METHOD_POST'] = 'POST';
GLOBAL['HTTP_METHOD_PUT'] = 'PUT';

GLOBAL['SIGN_IN_URL'] = GLOBAL['BASE_URL'] + '/user/loginAD';
GLOBAL['DISPLAY_ALL_ARTICLES_URL'] = GLOBAL['BASE_URL'] + '/article/getAllArticles';
GLOBAL['CREATE_ARTICLE'] = GLOBAL['BASE_URL'] + '/article/createArticle';
GLOBAL['EDIT_ARTICLE'] = GLOBAL['BASE_URL'] + '/article/editArticle/';
GLOBAL['GET_ARTICLE_BY_ID'] = GLOBAL['BASE_URL'] + '/article/getArticle/';
GLOBAL['LIKE'] = GLOBAL['BASE_URL'] + '/article/like/';
GLOBAL['DISLIKE'] = GLOBAL['BASE_URL'] + '/article/dislike/';
GLOBAL['COMMENT'] = GLOBAL['BASE_URL'] + '/article/comment/';
GLOBAL['GET_ALL_USERS'] = GLOBAL['BASE_URL'] + '/admin/getUsers';
GLOBAL['VIEW_ARTICLE'] = GLOBAL['BASE_URL'] + '/article/';
GLOBAL['DELETE_ARTICLE'] = GLOBAL['BASE_URL'] + '/article/';
GLOBAL['USER_LIST_BLOCK'] = GLOBAL['BASE_URL'] + '/admin/blockedUser/';
GLOBAL['SEARCH_GLOBAL'] = GLOBAL['BASE_URL'] + '/article/search';
GLOBAL['ARTICLES_LIST_BLOCK'] = GLOBAL['BASE_URL'] + '/admin/getArticles';
GLOBAL['GET_DRAFTS'] = GLOBAL['BASE_URL'] + '/trending/draftArticles';
GLOBAL['MY_TRENDING_ARTICLES'] = GLOBAL['BASE_URL'] + '/trending/trendingArticle';
GLOBAL['MY_BLOCKED_ARTICLES'] = GLOBAL['BASE_URL'] + '/trending/unApprovedArticles';
GLOBAL['MY_CREATED_ARTICLES'] = GLOBAL['BASE_URL'] + '/trending/getAllCreatedArticles';
GLOBAL['ADMIN_BLOCKED_ARTICLES'] = GLOBAL['BASE_URL'] + '/admin/blockedArticle/';
GLOBAL['SEARCH_ADVANCED'] = GLOBAL['BASE_URL'] + '/article/advancedSearch';
GLOBAL['BOOKMARKED_ARTICLE'] = GLOBAL['BASE_URL'] + '/trending/postSavedArticle/';
GLOBAL['GET_BOOKMARKED_ARTICLES'] = GLOBAL['BASE_URL'] + '/trending/savedArticles';
